name: CI
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       FLOW_PROJECT_CODE: "wFy45eKc4a4hWgaI"
       FLOW_API_URL: 'https://homologa.convisoappsec.com' 
   steps:
   - uses: actions/checkout@v2

   - name: Run SAST
     run: conviso sast run

   - name: Run SCA
     run: conviso sca run

   - name: Run Sec Gate
     run: conviso vulnerability assert-security-rules --rules-file conviso-sec-gate-rules.yml
